tes_bo_homepage:
    path:     /
    defaults: { _controller: TesBoBundle:Default:index }

tes_bo_about:
    path:     /Apropos
    defaults: { _controller: TesBoBundle:Default:about }

tes_bo_register:
    path:     /BecomeBo
    defaults: { _controller: TesBoBundle:Default:register }
