<?php

namespace TesBoBundle\Repository;

/**
 * GaleriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriesRepository extends \Doctrine\ORM\EntityRepository
{
}
