<?php

namespace TesBoBundle\Repository;

/**
 * GalleriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleriesRepository extends \Doctrine\ORM\EntityRepository
{
}
