<?php

namespace TesBoBundle\Repository;

/**
 * MediaTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
